version: '3.9'
services:
  db:
    volumes:
      - ".${PLATFORM_TYPE}mysql-volume:/var/lib/mysql"

  app:
    volumes:
      - ".${PLATFORM_TYPE}myApp:/var/www/html"
      - ".${PLATFORM_TYPE}start.sh:/start.sh"

  scheduler:
    volumes:
      - ".${PLATFORM_TYPE}myApp:/var/www/html"

  queue:
    volumes:
      - ".${PLATFORM_TYPE}myApp:/var/www/html"
