version: '3.9'
services:

  app:
    build: .
    image: earnie-app
    container_name: earnie-app
    ports:
      - "90:80"
    environment:
      APP_ENV: development
      CONTAINER_ROLE: app
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
      DB_HOST: earnie-db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - earnie
    depends_on:
      db:
        condition: service_healthy

  scheduler:
    image: earnie-app
    container_name: earnie-scheduler
    environment:
      APP_ENV: development
      CONTAINER_ROLE: scheduler
      DB_HOST: earnie-db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - earnie
    depends_on:
      - app

  queue:
    image: earnie-app
    container_name: earnie-queue
    environment:
      APP_ENV: development
      CONTAINER_ROLE: queue
      DB_HOST: earnie-db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - earnie
    depends_on:
      - app

  db:
    # platform: linux/x86_64
    image: mysql:${MYSQL_VERSION}
    restart: always
    container_name: earnie-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - earnie
    healthcheck:
      test: [ "CMD", "mysqladmin" , "-p${MYSQL_ROOT_PASSWORD}", "ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

networks:
  earnie:
    driver: bridge

volumes:
  app:
    driver: local
  db:
    driver: local
