# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: region1storageclass
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2
#   encrypted: "true"
# volumeBindingMode: WaitForFirstConsumer
# allowedTopologies:
# - matchLabelExpressions:
#   - key: failure-domain.beta.kubernetes.io/zone
#     values:
#     - eu-west-1a
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: region1storageclass