version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build
          command: docker-compose -f docker-compose.yml build
      - run:
          name: Start containers and verify app is working
          command: |
            set -x
            docker-compose -f docker-compose.yml up -d
            docker run --network container:earnie-app \
              appropriate/curl --ipv4 --retry 15 --retry-delay 10 --retry-connrefused http://localhost:80/healthz
      - run:
          name: Run Tests
          command: docker exec -t earnie-app php artisan test --parallel

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: test

