apiVersion: v1
kind: ConfigMap
metadata:
  name: gip-app-config
  namespace: earnie-bump
  labels:
    app: gip-app
data:
  APP_URL: https://bump.myearnie.co.uk/
  APP_NAME: "Earnie Bump App"
  APP_ENV: testing
  APP_DEBUG: "true"
  APP_SERVICE_NAME: gip-app-service
  OPEN_REGISTRATION_ALLOWED: "false"
  # DB settings
  DB_CONNECTION: mysql
  DB_HOST: lcpawsmysql-bump-myearnie.cjq8eonkhick.eu-west-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_DATABASE: gip
  DB_USERNAME: userBumpMyearnie
  # Mail settings
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
  MAIL_USERNAME: bumpspacetest@gmail.com
  MAIL_ENCRYPTION: tls
  # KPI settings
  KPI_DATA_TYPE: fraction
  KPI_AGGREGATION_METHOD: weightedaverage
  KPI_BASE_PERIOD: weekly
  KPI_SCORE_UNIT: '%'
  # AWS settings
  # AWS_ACCESS_KEY_ID:
  # AWS_DEFAULT_REGION: eu-west-1
  # AWS_BUCKET:
  # Password settings
  PASSWORD_EXPIRE_SECURITY: "false"
  EXPIRE_PASSWORD_IN_DAYS: "45"
  LOGIN_ATTEMPTS_BEFORE_LOCK: "4"
  PASSWORD_LOCK_TIME_IN_MINUTES: "1"
  PASSWORD_VALIDATION_MAX: "120"

  IOS_DEEPLINK: '{"applinks":{"apps":[],"details":[{"appID":"52Z2DK4SRR.uk.co.lightfoot.bump-app","paths":["NOT/_/*","/*"]}]}}'
  ANDROID_DEEPLINK: '[{"relation": ["delegate_permission/common.handle_all_urls"],"target": {"namespace": "android_app","package_name": "uk.co.lightfoot.bump.app","sha256_cert_fingerprints":["CF:91:22:A8:F0:66:CA:5C:08:54:F3:9C:B4:17:17:3E:DE:6C:1A:01:85:8F:0D:7E:5B:68:D8:F4:6C:B8:1C:FD"]}}]'