apiVersion: v1
kind: ConfigMap
metadata:
  name: gip-app-config
  namespace: earnie-staging
  labels:
    app: gip-app
data:
  # App Settings
  APP_URL: https://dev-earnie.lightfoot.co.uk/
  APP_NAME: "Earnie App"
  APP_ENV: staging
  APP_KEY: base64:f3EIHwG4mkadworzcgN3wK0VFuetQkZi0vfi8Eff6MI=
  APP_DEBUG: "true"
  APP_SERVICE_NAME: gip-app-service
  OPEN_REGISTRATION_ALLOWED: "true"
  GENERATE_USERNAMES: "true"
  EXTERNAL_ID_LABEL: ""

  # DB settings
  DB_CONNECTION: mysql
  DB_HOST: lcpawsmysql-myearnie-dev-staging.cjq8eonkhick.eu-west-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_DATABASE: gip
  DB_USERNAME: userStagingMyEarnie

  # Mail settings
  MAIL_MAILER: sparkpost
  MAIL_FROM_ADDRESS: earnie@lightfoot.co.uk
  ACCOUNTING_MAIL_ADDRESS: gipapp.test@gmail.com

  # KPI settings
  KPI_DATA_TYPE: fraction
  KPI_AGGREGATION_METHOD: weightedaverage
  KPI_BASE_PERIOD: weekly
  KPI_SCORE_UNIT: "%"

  # File Storage Settings
  FILESYSTEM_DRIVER: local
  # AWS_ACCESS_KEY_ID:
  # AWS_DEFAULT_REGION: eu-west-1
  # AWS_BUCKET:

  # Password settings
  PASSWORD_EXPIRE_SECURITY: "false"
  EXPIRE_PASSWORD_IN_DAYS: "45"
  LOGIN_ATTEMPTS_BEFORE_LOCK: "4"
  PASSWORD_LOCK_TIME_IN_MINUTES: "1"
  PASSWORD_VALIDATION_MAX: "120"
  PASSWORD_VALIDATION_REGEX4: "@$!%*#?&-_"

  IOS_DEEPLINK: '{"applinks":{"apps":[],"details":[{"appID":"52Z2DK4SRR.uk.co.lightfoot.earnie-app","paths":["NOT/_/*","/*"]}]}}'
  ANDROID_DEEPLINK: '[{"relation":["delegate_permission/common.handle_all_urls"],"target":{"namespace":"android_app","package_name":"uk.co.lightfoot.earnie.app","sha256_cert_fingerprints":["CF:91:22:A8:F0:66:CA:5C:08:54:F3:9C:B4:17:17:3E:DE:6C:1A:01:85:8F:0D:7E:5B:68:D8:F4:6C:B8:1C:FD"]}},{"relation":"delegate_permission/common.get_login_creds"],"target":{"namespace":"web","site":"https://dev-earnie.lightfoot.co.uk"}},{"relation":["delegate_permission/common.get_login_creds"],"target":{"namespace":"android_app","package_name":"uk.co.lightfoot.earnie.app","sha256_cert_fingerprints":["CF:91:22:A8:F0:66:CA:5C:08:54:F3:9C:B4:17:17:3E:DE:6C:1A:01:85:8F:0D:7E:5B:68:D8:F4:6C:B8:1C:FD"]}}]'

  XDEBUG_CONFIG: remote_host=54b2689c4cdb.ngrok.io remote_port=80 remote_enable=1