apiVersion: apps/v1
kind: Deployment
metadata:
  name: gip-admin-portal
  namespace: earnie-tesco-pickers-beta
spec:
  selector:
    matchLabels:
      app: gip-admin-portal
  template:
    metadata:
      labels:
        app: gip-admin-portal
    spec:
      containers:
        - name: gip-admin-portal
          image: ashwoodslightfoot/earnie-admin-portal:1.0.5
          resources: {}
          env:
            - name: NODE_ENV
              value: production
            - name: BASE_URL
              value: https://tesco-pickers-beta.myearnie.co.uk/
            - name: BROWSER_BASE_URL
              value: https://tesco-pickers-beta.myearnie.co.uk/
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /login
              port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gip-admin-portal
spec:
  selector:
    app: gip-admin-portal
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP